use std::{fs,path::PathBuf,io::Write,process::{Command,Stdio}};
fn main() {
    let root=PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let mut arms=String::new();let mut names=Vec::new();
    for module in ["ai","audit","bizapps","cards","groups","knowledge","messaging","moderation","rules","summaries","tasks"] {
        let file=syn::parse_file(&fs::read_to_string(root.join(format!("tauri3/src-tauri/src/commands/{module}.rs"))).unwrap()).unwrap();
        for item in file.items {
            let syn::Item::Fn(function)=item else {continue};
            if !function.attrs.iter().any(|a|a.path().is_ident("cfg_attr")) {continue;}
            let name=function.sig.ident.to_string();let mut args=Vec::new();
            for input in &function.sig.inputs {
                let syn::FnArg::Typed(arg)=input else {panic!("Unexpected receiver")};
                let syn::Pat::Ident(pat)=arg.pat.as_ref() else {panic!("Unexpected pattern")};
                let key=pat.ident.to_string();
                args.push(match key.as_str(){
                    "state"=>"State(state)".into(),"app"=>"state.events.clone()".into(),
                    _=>{let mut words=key.split('_');let mut camel=words.next().unwrap().to_owned();for word in words {let mut chars=word.chars();camel.extend(chars.next().unwrap().to_uppercase());camel.extend(chars);}format!("argument(&args, {camel:?})?")}
                });
            }
            let awaited=if function.sig.asyncness.is_some(){".await"}else{""};
            arms.push_str(&format!("        {name:?} => serde_json::to_value(crate::shared_commands::{module}::{name}({}){awaited}?).map_err(|_| AppError::new(\"web_encode\", \"Response encoding failed\")),\n",args.join(", ")));
            names.push(name);
        }
    }
    names.sort();
    let output=format!("// Generated by tools/web-dispatch-generator; do not edit by hand.\n\
pub const WEB_COMMANDS: &[&str] = &{names:?};\n\
fn argument<T:serde::de::DeserializeOwned>(args:&serde_json::Value,key:&str)->AppResult<T>{{\n\
    serde_json::from_value(args.get(key).cloned().unwrap_or(serde_json::Value::Null)).map_err(|_|AppError::new(\"invalid_argument\",format!(\"Invalid parameter: {{key}}\")))\n\
}}\n\
pub async fn dispatch(state:&AppState,name:&str,args:serde_json::Value)->AppResult<serde_json::Value>{{\n\
    match name {{\n{arms}        _ => Err(AppError::new(\"unknown_command\", \"Unknown Web command\")),\n    }}\n}}\n");
    let mut formatter=Command::new("rustfmt").args(["--edition","2021"]).stdin(Stdio::piped()).stdout(Stdio::piped()).spawn().expect("rustfmt");
    formatter.stdin.take().unwrap().write_all(output.as_bytes()).unwrap();
    let formatted=formatter.wait_with_output().unwrap();assert!(formatted.status.success());
    let output=String::from_utf8(formatted.stdout).unwrap();
    let path=root.join("crates/dh-core/src/web_dispatch.rs");
    if std::env::args().any(|a|a=="--check") {assert_eq!(fs::read_to_string(path).unwrap(),output,"Regenerate Web command dispatch");}
    else {fs::write(path,output).unwrap();}
    println!("Web commands: {}",names.len());
}
