#[path = "../../../tauri3/src-tauri/src/commands/ai.rs"]
pub(crate) mod ai;
#[path = "../../../tauri3/src-tauri/src/commands/audit.rs"]
pub(crate) mod audit;
#[path = "../../../tauri3/src-tauri/src/commands/bizapps.rs"]
pub(crate) mod bizapps;
#[path = "../../../tauri3/src-tauri/src/commands/cards.rs"]
pub(crate) mod cards;
#[path = "../../../tauri3/src-tauri/src/commands/groups.rs"]
pub(crate) mod groups;
#[path = "../../../tauri3/src-tauri/src/commands/knowledge.rs"]
pub(crate) mod knowledge;
#[path = "../../../tauri3/src-tauri/src/commands/messaging.rs"]
pub(crate) mod messaging;
#[path = "../../../tauri3/src-tauri/src/commands/moderation.rs"]
pub(crate) mod moderation;
#[path = "../../../tauri3/src-tauri/src/commands/rules.rs"]
pub(crate) mod rules;
#[path = "../../../tauri3/src-tauri/src/commands/summaries.rs"]
pub(crate) mod summaries;
#[path = "../../../tauri3/src-tauri/src/commands/tasks.rs"]
pub(crate) mod tasks;
