// Generated by tools/web-dispatch-generator; do not edit by hand.
pub const WEB_COMMANDS: &[&str] = &[
    "apply_card_names",
    "bind_knowledge_base",
    "clone_knowledge_base",
    "create_knowledge_base",
    "delete_activity",
    "delete_ai_provider_endpoint",
    "delete_group_announcement",
    "delete_knowledge_base",
    "delete_knowledge_document",
    "delete_rule",
    "delete_schedule",
    "delete_task",
    "execute_group_batch",
    "execute_member_batch",
    "export_audit",
    "export_rules",
    "generate_daily_summary",
    "get_ai_automation_settings",
    "get_ai_settings",
    "get_business_app_health",
    "get_card_settings",
    "get_group_announcement",
    "get_group_management_context",
    "get_group_mute_state",
    "get_summary_settings",
    "import_rules",
    "list_activities",
    "list_activity_runs",
    "list_ai_provider_endpoints",
    "list_audit",
    "list_business_app_runs",
    "list_business_apps",
    "list_cached_groups",
    "list_card_rename_jobs",
    "list_daily_summaries",
    "list_group_announcements",
    "list_groups",
    "list_knowledge_bases",
    "list_knowledge_bindings",
    "list_knowledge_documents",
    "list_members",
    "list_rules",
    "list_schedule_runs",
    "list_schedules",
    "list_tasks",
    "local_members",
    "mute_member",
    "preview_activity_text",
    "preview_card_names",
    "publish_activity_now",
    "query_audit",
    "query_messages",
    "recall_message",
    "recent_messages",
    "remove_member",
    "rename_member",
    "retry_card_rename_jobs",
    "save_activity",
    "save_ai_automation_settings",
    "save_ai_provider_endpoint",
    "save_ai_settings",
    "save_card_settings",
    "save_group_welcome",
    "save_knowledge_document",
    "save_rule",
    "save_schedule",
    "save_summary_settings",
    "save_task",
    "search_rule_members",
    "send_text",
    "send_text_batch",
    "set_business_app_enabled",
    "set_group_announcement",
    "set_group_features",
    "set_group_mute",
    "set_group_rule_features",
    "test_ai",
    "test_ai_provider_endpoint",
    "test_business_app",
    "unmute_member",
    "update_group_announcement",
    "update_knowledge_base",
];
fn argument<T: serde::de::DeserializeOwned>(args: &serde_json::Value, key: &str) -> AppResult<T> {
    serde_json::from_value(args.get(key).cloned().unwrap_or(serde_json::Value::Null))
        .map_err(|_| AppError::new("invalid_argument", format!("Invalid parameter: {key}")))
}
pub async fn dispatch(
    state: &AppState,
    name: &str,
    args: serde_json::Value,
) -> AppResult<serde_json::Value> {
    match name {
        "get_ai_settings" => {
            serde_json::to_value(crate::shared_commands::ai::get_ai_settings(State(state)).await?)
                .map_err(|_| AppError::new("web_encode", "Response encoding failed"))
        }
        "get_ai_automation_settings" => serde_json::to_value(
            crate::shared_commands::ai::get_ai_automation_settings(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_ai_automation_settings" => serde_json::to_value(
            crate::shared_commands::ai::save_ai_automation_settings(
                State(state),
                argument(&args, "settings")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_ai_settings" => serde_json::to_value(
            crate::shared_commands::ai::save_ai_settings(
                State(state),
                argument(&args, "baseUrl")?,
                argument(&args, "webhookUrl")?,
                argument(&args, "apiBackend")?,
                argument(&args, "model")?,
                argument(&args, "apiKey")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_ai_provider_endpoints" => serde_json::to_value(
            crate::shared_commands::ai::list_ai_provider_endpoints(
                State(state),
                argument(&args, "accountId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_ai_provider_endpoint" => serde_json::to_value(
            crate::shared_commands::ai::save_ai_provider_endpoint(
                State(state),
                argument(&args, "input")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "delete_ai_provider_endpoint" => serde_json::to_value(
            crate::shared_commands::ai::delete_ai_provider_endpoint(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "endpointId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "test_ai_provider_endpoint" => serde_json::to_value(
            crate::shared_commands::ai::test_ai_provider_endpoint(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "endpointId")?,
                argument(&args, "message")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "test_ai" => serde_json::to_value(
            crate::shared_commands::ai::test_ai(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "message")?,
                argument(&args, "recentContext")?,
                argument(&args, "includeBuiltInKnowledge")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_audit" => serde_json::to_value(
            crate::shared_commands::audit::list_audit(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "limit")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "query_audit" => serde_json::to_value(
            crate::shared_commands::audit::query_audit(State(state), argument(&args, "query")?)
                .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "export_audit" => serde_json::to_value(
            crate::shared_commands::audit::export_audit(
                State(state),
                argument(&args, "query")?,
                argument(&args, "format")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_business_apps" => serde_json::to_value(
            crate::shared_commands::bizapps::list_business_apps(
                State(state),
                argument(&args, "accountId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "set_business_app_enabled" => serde_json::to_value(
            crate::shared_commands::bizapps::set_business_app_enabled(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "appId")?,
                argument(&args, "enabled")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "get_business_app_health" => serde_json::to_value(
            crate::shared_commands::bizapps::get_business_app_health(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "appId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_business_app_runs" => serde_json::to_value(
            crate::shared_commands::bizapps::list_business_app_runs(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "appId")?,
                argument(&args, "limit")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "test_business_app" => serde_json::to_value(
            crate::shared_commands::bizapps::test_business_app(
                State(state),
                argument(&args, "input")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "preview_card_names" => serde_json::to_value(
            crate::shared_commands::cards::preview_card_names(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
                argument(&args, "prefix")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "apply_card_names" => serde_json::to_value(
            crate::shared_commands::cards::apply_card_names(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "plans")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_card_rename_jobs" => serde_json::to_value(
            crate::shared_commands::cards::list_card_rename_jobs(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
                argument(&args, "limit")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "retry_card_rename_jobs" => serde_json::to_value(
            crate::shared_commands::cards::retry_card_rename_jobs(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "get_card_settings" => serde_json::to_value(
            crate::shared_commands::cards::get_card_settings(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_card_settings" => serde_json::to_value(
            crate::shared_commands::cards::save_card_settings(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
                argument(&args, "prefix")?,
                argument(&args, "autoRename")?,
                argument(&args, "paused")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_group_welcome" => serde_json::to_value(
            crate::shared_commands::cards::save_group_welcome(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
                argument(&args, "welcomeMessage")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_groups" => {
            serde_json::to_value(crate::shared_commands::groups::list_groups(State(state)).await?)
                .map_err(|_| AppError::new("web_encode", "Response encoding failed"))
        }
        "list_cached_groups" => serde_json::to_value(
            crate::shared_commands::groups::list_cached_groups(State(state)).await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_members" => serde_json::to_value(
            crate::shared_commands::groups::list_members(
                state.events.clone(),
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "refresh")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "local_members" => serde_json::to_value(
            crate::shared_commands::groups::local_members(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "set_group_features" => serde_json::to_value(
            crate::shared_commands::groups::set_group_features(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
                argument(&args, "enabled")?,
                argument(&args, "aiEnabled")?,
                argument(&args, "moderationEnabled")?,
                argument(&args, "manualTakeover")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_knowledge_bases" => serde_json::to_value(
            crate::shared_commands::knowledge::list_knowledge_bases(
                State(state),
                argument(&args, "accountId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "create_knowledge_base" => serde_json::to_value(
            crate::shared_commands::knowledge::create_knowledge_base(
                State(state),
                argument(&args, "base")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "update_knowledge_base" => serde_json::to_value(
            crate::shared_commands::knowledge::update_knowledge_base(
                State(state),
                argument(&args, "base")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "clone_knowledge_base" => serde_json::to_value(
            crate::shared_commands::knowledge::clone_knowledge_base(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "baseId")?,
                argument(&args, "name")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "delete_knowledge_base" => serde_json::to_value(
            crate::shared_commands::knowledge::delete_knowledge_base(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "baseId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_knowledge_documents" => serde_json::to_value(
            crate::shared_commands::knowledge::list_knowledge_documents(
                State(state),
                argument(&args, "baseId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_knowledge_document" => serde_json::to_value(
            crate::shared_commands::knowledge::save_knowledge_document(
                State(state),
                argument(&args, "document")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "delete_knowledge_document" => serde_json::to_value(
            crate::shared_commands::knowledge::delete_knowledge_document(
                State(state),
                argument(&args, "baseId")?,
                argument(&args, "documentId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "bind_knowledge_base" => serde_json::to_value(
            crate::shared_commands::knowledge::bind_knowledge_base(
                State(state),
                argument(&args, "baseId")?,
                argument(&args, "accountId")?,
                argument(&args, "groupIds")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_knowledge_bindings" => serde_json::to_value(
            crate::shared_commands::knowledge::list_knowledge_bindings(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "baseId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "send_text" => serde_json::to_value(
            crate::shared_commands::messaging::send_text(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "text")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "send_text_batch" => serde_json::to_value(
            crate::shared_commands::messaging::send_text_batch(
                State(state),
                argument(&args, "groupIds")?,
                argument(&args, "text")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "execute_group_batch" => serde_json::to_value(
            crate::shared_commands::messaging::execute_group_batch(
                State(state),
                argument(&args, "input")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "query_messages" => serde_json::to_value(
            crate::shared_commands::messaging::query_messages(
                State(state),
                argument(&args, "query")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "recent_messages" => serde_json::to_value(
            crate::shared_commands::messaging::recent_messages(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
                argument(&args, "limit")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "recall_message" => serde_json::to_value(
            crate::shared_commands::moderation::recall_message(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "senderUserId")?,
                argument(&args, "messageId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "mute_member" => serde_json::to_value(
            crate::shared_commands::moderation::mute_member(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "userId")?,
                argument(&args, "durationSeconds")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "unmute_member" => serde_json::to_value(
            crate::shared_commands::moderation::unmute_member(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "userId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "rename_member" => serde_json::to_value(
            crate::shared_commands::moderation::rename_member(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "member")?,
                argument(&args, "nickname")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "remove_member" => serde_json::to_value(
            crate::shared_commands::moderation::remove_member(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "userId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "set_group_mute" => serde_json::to_value(
            crate::shared_commands::moderation::set_group_mute(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "muted")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "get_group_mute_state" => serde_json::to_value(
            crate::shared_commands::moderation::get_group_mute_state(
                State(state),
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "set_group_announcement" => serde_json::to_value(
            crate::shared_commands::moderation::set_group_announcement(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "text")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "get_group_announcement" => serde_json::to_value(
            crate::shared_commands::moderation::get_group_announcement(
                State(state),
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_group_announcements" => serde_json::to_value(
            crate::shared_commands::moderation::list_group_announcements(
                State(state),
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "update_group_announcement" => serde_json::to_value(
            crate::shared_commands::moderation::update_group_announcement(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "noticeId")?,
                argument(&args, "text")?,
                argument(&args, "mode")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "delete_group_announcement" => serde_json::to_value(
            crate::shared_commands::moderation::delete_group_announcement(
                State(state),
                argument(&args, "groupId")?,
                argument(&args, "noticeId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "get_group_management_context" => serde_json::to_value(
            crate::shared_commands::moderation::get_group_management_context(
                State(state),
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "execute_member_batch" => serde_json::to_value(
            crate::shared_commands::moderation::execute_member_batch(
                State(state),
                argument(&args, "input")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_rules" => serde_json::to_value(
            crate::shared_commands::rules::list_rules(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "set_group_rule_features" => serde_json::to_value(
            crate::shared_commands::rules::set_group_rule_features(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
                argument(&args, "machineEnabled")?,
                argument(&args, "aiEnabled")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "search_rule_members" => serde_json::to_value(
            crate::shared_commands::rules::search_rule_members(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupIds")?,
                argument(&args, "keyword")?,
                argument(&args, "cursor")?,
                argument(&args, "limit")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_rule" => serde_json::to_value(
            crate::shared_commands::rules::save_rule(State(state), argument(&args, "rule")?)
                .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "delete_rule" => serde_json::to_value(
            crate::shared_commands::rules::delete_rule(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "ruleId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "export_rules" => serde_json::to_value(
            crate::shared_commands::rules::export_rules(
                State(state),
                argument(&args, "accountId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "import_rules" => serde_json::to_value(
            crate::shared_commands::rules::import_rules(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "json")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_daily_summaries" => serde_json::to_value(
            crate::shared_commands::summaries::list_daily_summaries(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "limit")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "get_summary_settings" => serde_json::to_value(
            crate::shared_commands::summaries::get_summary_settings(
                State(state),
                argument(&args, "accountId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_summary_settings" => serde_json::to_value(
            crate::shared_commands::summaries::save_summary_settings(
                State(state),
                argument(&args, "settings")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "generate_daily_summary" => serde_json::to_value(
            crate::shared_commands::summaries::generate_daily_summary(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_tasks" => serde_json::to_value(
            crate::shared_commands::tasks::list_tasks(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_task" => serde_json::to_value(
            crate::shared_commands::tasks::save_task(State(state), argument(&args, "task")?)
                .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "delete_task" => serde_json::to_value(
            crate::shared_commands::tasks::delete_task(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "taskId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_activities" => serde_json::to_value(
            crate::shared_commands::tasks::list_activities(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "includeDeleted")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_activity" => serde_json::to_value(
            crate::shared_commands::tasks::save_activity(
                State(state),
                argument(&args, "activity")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "delete_activity" => serde_json::to_value(
            crate::shared_commands::tasks::delete_activity(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "activityId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_activity_runs" => serde_json::to_value(
            crate::shared_commands::tasks::list_activity_runs(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "activityId")?,
                argument(&args, "limit")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "preview_activity_text" => serde_json::to_value(
            crate::shared_commands::tasks::preview_activity_text(
                State(state),
                argument(&args, "activity")?,
                argument(&args, "groupId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "publish_activity_now" => serde_json::to_value(
            crate::shared_commands::tasks::publish_activity_now(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "activityId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_schedules" => serde_json::to_value(
            crate::shared_commands::tasks::list_schedules(
                State(state),
                argument(&args, "accountId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "save_schedule" => serde_json::to_value(
            crate::shared_commands::tasks::save_schedule(
                State(state),
                argument(&args, "schedule")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "delete_schedule" => serde_json::to_value(
            crate::shared_commands::tasks::delete_schedule(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "scheduleId")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        "list_schedule_runs" => serde_json::to_value(
            crate::shared_commands::tasks::list_schedule_runs(
                State(state),
                argument(&args, "accountId")?,
                argument(&args, "scheduleId")?,
                argument(&args, "limit")?,
            )
            .await?,
        )
        .map_err(|_| AppError::new("web_encode", "Response encoding failed")),
        _ => Err(AppError::new("unknown_command", "Unknown Web command")),
    }
}
