import { CheckCircle2, Database, RefreshCw, Wifi, WifiOff } from 'lucide-react'
import type { ReactNode } from 'react'
import type { Diagnostic } from '../runtimeTypes'
import type { Audit, DailySummary, DatabaseStatus, Group } from '../types'
import { EmptyState, SectionHeading } from '../components/PageState'

export default function OverviewPage({ diagnostic, database, groups, audits, summaries, loading, refresh }: { diagnostic: Diagnostic | null; database: DatabaseStatus | null; groups: Group[]; audits: Audit[]; summaries: DailySummary[]; loading: boolean; refresh: () => void }) {
  const connecting = diagnostic?.status === 'starting' || diagnostic?.status === 'unavailable' || diagnostic?.status === 'devtools-ready' || diagnostic?.status === 'nim-not-ready'
  const heroTitle = diagnostic?.status === 'ready' ? '连接已准备好。' : diagnostic?.status === 'nim-not-ready' || diagnostic?.status === 'devtools-ready' ? '需要您登录账号。' : connecting ? '正在连接旺商聊。' : '先连接旺商聊，再开始管理。'
  return <div className="page-stack"><div className="overview-grid"><article className="hero-panel"><span className="eyebrow">工作区状态</span><h2>{heroTitle}</h2><p>{diagnostic?.detail || '正在检查旺商聊、DevTools 和登录状态。'}</p><button className="primary" onClick={refresh} disabled={loading}><RefreshCw size={15} className={loading ? 'spin' : ''} />立即检查</button></article><Metric icon={diagnostic?.status === 'ready' ? <Wifi size={17} /> : <WifiOff size={17} />} ok={diagnostic?.status === 'ready'} label="旺商聊" value={diagnostic ? statusText(diagnostic.status) : '检查中'} detail={diagnostic?.nimAccount || (diagnostic?.status === 'nim-not-ready' || diagnostic?.status === 'devtools-ready' ? '等待账号登录' : '尚未读取账号')} /><Metric icon={<Database size={17} />} label="本地数据库" value={database ? `${database.groups} 个群` : '未打开'} detail={database?.path || '等待初始化'} /><Metric icon={<CheckCircle2 size={17} />} label="AI 自动化群" value={`${groups.filter(group => group.enabled && group.aiEnabled).length} 个`} detail="每个群可单独配置 AI 权限" /></div>{summaries.length > 0 && <section className="section"><SectionHeading eyebrow="仅本机可见" title="每日摘要" meta={`${summaries.length} 条`} /><div className="summary-list compact">{summaries.slice(0, 4).map(summary => <article className="summary-item" key={summary.id}><div><strong>{groups.find(group => group.groupId === summary.groupId)?.name || `群 ${summary.groupId}`}</strong><time>{summary.localDate}</time></div><p>{summary.content}</p></article>)}</div></section>}<section className="section"><SectionHeading eyebrow="最近自动动作" title="审计记录" meta={`${audits.length} 条`} />{audits.length ? <div className="table">{audits.slice(0, 8).map(audit => <div className="table-row" key={audit.id}><strong>{auditLabel(audit.event)}</strong><span>{audit.details}</span><time>{audit.createdAt}</time></div>)}</div> : <EmptyState title="还没有审计记录" detail="连接并启用群后，规则和 AI 操作会显示在这里。" />}</section></div>
}
function Metric({ icon, label, value, detail, ok }: { icon: ReactNode; label: string; value: string; detail: string; ok?: boolean }) { return <article className="metric"><span className={`metric-icon ${ok ? 'ok' : ''}`}>{icon}</span><span className="eyebrow">{label}</span><strong>{value}</strong><p title={detail}>{detail}</p></article> }
export function statusText(value: string) { return ({ ready: '已连接', 'nim-not-ready': '等待登录', 'devtools-ready': '等待登录', unavailable: '连接异常', 'other-service': '端口被占用', starting: '启动中', 'running-without-devtools': '需要重启', 'restart-required': '需要重启' } as Record<string, string>)[value] ?? value }
function auditLabel(value: string) { return ({ message_received: '收到消息', rule_matched: '规则命中', action_executed: '执行群管动作', ai_reply: 'AI 回复', member_joined: '成员入群', member_left: '成员离群', card_renamed: '群名片修改', schedule_open: '定时开群', schedule_close: '定时关群', daily_summary: '生成每日摘要' } as Record<string, string>)[value] || value }
