import { useEffect, useState } from 'react'
import { CalendarClock, CheckCircle2, ClipboardList, Plus, RefreshCw, Save, Trash2 } from 'lucide-react'
import { api, readableError } from '../api/client'
import { EmptyState, PageFeedback, SectionHeading } from '../components/PageState'
import SelectField from '../components/SelectField'
import type { DailySummary, Group, LoadState, Schedule, ScheduleRun, SummarySettings, TaskItem } from '../types'

const newTask = (accountId: string, groupId: number): TaskItem => ({ id: 0, accountId, groupId, title: '', description: '', status: 'pending', assigneeId: 0, createdBy: 0, dueAt: null, reminderAt: null, reminderSentAt: null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() })
const newSchedule = (accountId: string): Schedule => ({ id: 0, accountId, name: '每日群发言', enabled: false, openTime: '08:00', closeTime: '22:00', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'Asia/Shanghai', groupIds: [] })

export default function PlansPage({ accountId, groups, onError }: { accountId: string; groups: Group[]; onError: (value: string) => void }) {
  const [tab, setTab] = useState<'tasks'|'schedules'|'summaries'>('tasks'); const [tasks, setTasks] = useState<TaskItem[]>([]); const [schedules, setSchedules] = useState<Schedule[]>([]); const [summaries, setSummaries] = useState<DailySummary[]>([]); const [scheduleRuns, setScheduleRuns] = useState<ScheduleRun[]>([]); const [summaryGroup, setSummaryGroup] = useState(0); const [summaryBusy, setSummaryBusy] = useState(false); const [summarySettings, setSummarySettings] = useState<SummarySettings>({ accountId: '', enabled: false, time: '23:00', groupIds: [], timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'Asia/Shanghai' }); const [editingTask, setEditingTask] = useState<TaskItem | null>(null); const [editingSchedule, setEditingSchedule] = useState<Schedule | null>(null); const [state, setState] = useState<LoadState>('idle')
  const reload = async (selection?: { taskId?: number; scheduleId?: number }) => { if (!accountId) { setTasks([]); setSchedules([]); setSummaries([]); setState('empty'); return }; setState('loading'); try { const [nextTasks, nextSchedules, nextSummaries, nextSummarySettings] = await Promise.all([api.listTasks(accountId), api.listSchedules(accountId), api.listSummaries(accountId), api.getSummarySettings(accountId)]); setTasks(nextTasks); setSchedules(nextSchedules); setSummaries(nextSummaries); setSummarySettings(nextSummarySettings); setEditingTask(current => selection?.taskId ? nextTasks.find(task => task.id === selection.taskId) || current || newTask(accountId, groups[0]?.groupId || 0) : current || nextTasks[0] || newTask(accountId, groups[0]?.groupId || 0)); setEditingSchedule(current => selection?.scheduleId ? nextSchedules.find(schedule => schedule.id === selection.scheduleId) || current || newSchedule(accountId) : current || nextSchedules[0] || newSchedule(accountId)); setState(nextTasks.length || nextSchedules.length || nextSummaries.length ? 'ready' : 'empty') } catch (reason) { onError(readableError(reason)); setState(tasks.length || schedules.length || summaries.length ? 'offlineCached' : 'error') } }
  useEffect(() => { void reload() }, [accountId])
  useEffect(() => { if (!editingSchedule?.id) { setScheduleRuns([]); return }; void api.listScheduleRuns(accountId, editingSchedule.id).then(setScheduleRuns).catch(reason => onError(readableError(reason))) }, [accountId, editingSchedule?.id])
  const saveTask = async () => { if (!editingTask?.title.trim()) { onError('任务标题不能为空'); return }; try { const id = await api.saveTask(editingTask); await reload({ taskId: id }) } catch (reason) { onError(readableError(reason)) } }
  const saveSchedule = async () => { if (!editingSchedule?.name.trim() || !editingSchedule.groupIds.length) { onError('计划名称和使用群不能为空'); return }; if (editingSchedule.openTime === editingSchedule.closeTime) { onError('开群和关群时间不能相同'); return }; try { const id = await api.saveSchedule(editingSchedule); await reload({ scheduleId: id }) } catch (reason) { onError(readableError(reason)) } }
  const removeTask = async () => { if (!editingTask?.id) return; try { await api.deleteTask(accountId, editingTask.id); setEditingTask(null); await reload() } catch (reason) { onError(readableError(reason)) } }
  const removeSchedule = async () => { if (!editingSchedule?.id) return; try { await api.deleteSchedule(accountId, editingSchedule.id); setEditingSchedule(null); await reload() } catch (reason) { onError(readableError(reason)) } }
  const generateSummary = async () => { const groupId = summaryGroup || groups[0]?.groupId; if (!groupId) { onError('请先选择群聊'); return }; setSummaryBusy(true); try { await api.generateSummary(accountId, groupId); await reload() } catch (reason) { onError(readableError(reason)) } finally { setSummaryBusy(false) } }
  const saveSummarySettings = async () => { if (summarySettings.enabled && !summarySettings.groupIds.length) { onError('启用每日摘要前请至少选择一个群'); return }; setSummaryBusy(true); try { await api.saveSummarySettings({ ...summarySettings, accountId }); await reload() } catch (reason) { onError(readableError(reason)) } finally { setSummaryBusy(false) } }
  return <div className="page-stack"><section className="section"><SectionHeading eyebrow="工作安排" title="任务与计划" meta={<span className="tabs"><button className={tab === 'tasks' ? 'active' : ''} onClick={() => setTab('tasks')}><ClipboardList size={14} />任务</button><button className={tab === 'schedules' ? 'active' : ''} onClick={() => setTab('schedules')}><CalendarClock size={14} />开关群计划</button><button className={tab === 'summaries' ? 'active' : ''} onClick={() => setTab('summaries')}><CheckCircle2 size={14} />每日摘要</button></span>} actions={<button className="secondary" onClick={() => void reload()}><RefreshCw size={15} />刷新</button>} /><PageFeedback state={state === 'empty' ? 'ready' : state} error="任务与计划读取失败" retry={() => void reload()} emptyTitle="暂无任务与计划" emptyDetail="可以新建任务、开关群计划或每日摘要。">
      {tab === 'tasks' && <TaskPanel tasks={tasks} editing={editingTask} setEditing={setEditingTask} accountId={accountId} groups={groups} onSave={() => void saveTask()} onDelete={() => void removeTask()} />}
      {tab === 'schedules' && <SchedulePanel schedules={schedules} runs={scheduleRuns} editing={editingSchedule} setEditing={setEditingSchedule} accountId={accountId} groups={groups} onSave={() => void saveSchedule()} onDelete={() => void removeSchedule()} />}
      {tab === 'summaries' && <div><div className="summary-settings"><label className="switch-field"><input type="checkbox" checked={summarySettings.enabled} onChange={event => setSummarySettings({ ...summarySettings, enabled: event.target.checked })} /><span>启用每日自动摘要</span></label><label>生成时间<input type="time" value={summarySettings.time} onChange={event => setSummarySettings({ ...summarySettings, time: event.target.value })} /></label><div className="group-filter"><span>摘要群</span>{groups.map(group => <label className={`check-chip ${summarySettings.groupIds.includes(group.groupId) ? 'selected' : ''}`} key={group.groupId}><input type="checkbox" checked={summarySettings.groupIds.includes(group.groupId)} onChange={() => setSummarySettings({ ...summarySettings, groupIds: summarySettings.groupIds.includes(group.groupId) ? summarySettings.groupIds.filter(id => id !== group.groupId) : [...summarySettings.groupIds, group.groupId] })} />{group.name}</label>)}</div><button className="secondary" disabled={summaryBusy} onClick={() => void saveSummarySettings()}><Save size={15} />保存摘要计划</button><small>按当前电脑时区 {summarySettings.time} 生成，只显示在本机总览。</small></div><div className="summary-toolbar"><label>手动选择群<select value={summaryGroup || groups[0]?.groupId || 0} onChange={event => setSummaryGroup(Number(event.target.value))}>{groups.map(group => <option value={group.groupId} key={group.groupId}>{group.name}</option>)}</select></label><button className="primary" disabled={summaryBusy || !groups.length} onClick={() => void generateSummary()}>{summaryBusy ? '生成中' : '生成今日摘要'}</button><span>摘要只在本机展示，不发送群聊。</span></div><PageFeedback state={state === 'loading' ? 'loading' : summaries.length ? 'ready' : 'empty'} emptyTitle="暂无每日摘要" emptyDetail="选择群并生成今日摘要，结果会同时显示在总览。"><div className="summary-list">{summaries.map(summary => <article className="summary-item" key={summary.id}><div><strong>{groups.find(group => group.groupId === summary.groupId)?.name || `群 ${summary.groupId}`}</strong><time>{summary.localDate}</time></div><p>{summary.content}</p></article>)}</div></PageFeedback></div>}
    </PageFeedback></section></div>
}

function TaskPanel({ tasks, editing, setEditing, accountId, groups, onSave, onDelete }: { tasks: TaskItem[]; editing: TaskItem | null; setEditing: (task: TaskItem) => void; accountId: string; groups: Group[]; onSave: () => void; onDelete: () => void }) { return <div className="work-layout"><div className="work-list">{tasks.map(task => <button className={`work-item ${editing?.id === task.id ? 'selected' : ''}`} key={task.id} onClick={() => setEditing(task)}><ClipboardList size={15} /><span><strong>{task.title}</strong><small>{task.status === 'done' ? '已完成' : '待处理'} · {task.dueAt ? new Date(task.dueAt).toLocaleDateString('zh-CN') : '无截止时间'}</small></span></button>)}<button className="new-line" onClick={() => setEditing(newTask(accountId, groups[0]?.groupId || 0))}><Plus size={15} />新建任务</button></div>{editing ? <div className="editor-panel"><div className="editor-title"><div><span className="eyebrow">任务编辑</span><h3>{editing.title || '未命名任务'}</h3></div><div className="button-row">{editing.id > 0 && <button className="secondary" onClick={onDelete}><Trash2 size={15} />删除</button>}<button className="primary" onClick={onSave}><Save size={15} />保存任务</button></div></div><div className="form-grid"><label>任务标题<input value={editing.title} onChange={event => setEditing({ ...editing, title: event.target.value })} /></label><SelectField label="所属群" value={String(editing.groupId || '')} options={groups.map(group => ({ value: String(group.groupId), label: group.name }))} disabled={!groups.length} onChange={value => setEditing({ ...editing, groupId: Number(value) })} /><label>负责人旺商号<input type="number" min="0" value={editing.assigneeId || ''} onChange={event => setEditing({ ...editing, assigneeId: Number(event.target.value) || 0 })} placeholder="留空为未指定" /></label><label>截止时间<input type="datetime-local" value={toLocalInput(editing.dueAt)} onChange={event => setEditing({ ...editing, dueAt: event.target.value ? new Date(event.target.value).toISOString() : null })} /></label><label>提醒时间<input type="datetime-local" value={toLocalInput(editing.reminderAt)} onChange={event => setEditing({ ...editing, reminderAt: event.target.value ? new Date(event.target.value).toISOString() : null, reminderSentAt: null })} /></label><SelectField label="状态" value={editing.status} options={[{ value: 'pending', label: '待处理' }, { value: 'done', label: '已完成' }, { value: 'cancelled', label: '已取消' }]} onChange={value => setEditing({ ...editing, status: value })} /><label className="wide-field">任务说明<textarea value={editing.description} onChange={event => setEditing({ ...editing, description: event.target.value })} placeholder="记录需要跟进的内容。" /></label></div></div> : <EmptyState title="选择任务" detail="创建任务后，这里可编辑负责人、截止时间和完成状态。" />}</div> }
function SchedulePanel({ schedules, runs, editing, setEditing, accountId, groups, onSave, onDelete }: { schedules: Schedule[]; runs: ScheduleRun[]; editing: Schedule | null; setEditing: (value: Schedule) => void; accountId: string; groups: Group[]; onSave: () => void; onDelete: () => void }) { return <div className="work-layout"><div className="work-list">{schedules.map(schedule => <button className={`work-item ${editing?.id === schedule.id ? 'selected' : ''}`} key={schedule.id} onClick={() => setEditing(schedule)}><CalendarClock size={15} /><span><strong>{schedule.name}</strong><small>每日 {schedule.openTime} 开群 / {schedule.closeTime} 关群</small></span><em className={schedule.enabled ? 'enabled' : ''}>{schedule.enabled ? '启用' : '停用'}</em></button>)}<button className="new-line" onClick={() => setEditing(newSchedule(accountId))}><Plus size={15} />新建计划</button></div>{editing ? <div className="editor-panel"><div className="editor-title"><div><span className="eyebrow">群发言计划</span><h3>{editing.name || '未命名计划'}</h3></div><div className="button-row">{editing.id > 0 && <button className="secondary" onClick={onDelete}><Trash2 size={15} />删除</button>}<button className="primary" onClick={onSave}><Save size={15} />保存计划</button></div></div><div className="form-grid"><label>计划名称<input value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })} /></label><label>时区<input value={editing.timezone} onChange={event => setEditing({ ...editing, timezone: event.target.value })} /></label><label>每日开群<input type="time" value={editing.openTime} onChange={event => setEditing({ ...editing, openTime: event.target.value })} /></label><label>每日关群<input type="time" value={editing.closeTime} onChange={event => setEditing({ ...editing, closeTime: event.target.value })} /></label><label className="switch-field"><input type="checkbox" checked={editing.enabled} onChange={event => setEditing({ ...editing, enabled: event.target.checked })} /><span>启用计划</span></label><div className="group-filter wide-field"><span>绑定群</span>{groups.map(group => <label className={`check-chip ${editing.groupIds.includes(group.groupId) ? 'selected' : ''}`} key={group.groupId}><input type="checkbox" checked={editing.groupIds.includes(group.groupId)} onChange={() => setEditing({ ...editing, groupIds: editing.groupIds.includes(group.groupId) ? editing.groupIds.filter(id => id !== group.groupId) : [...editing.groupIds, group.groupId] })} />{group.name}</label>)}</div></div>{runs.length > 0 && <div className="schedule-runs"><span className="eyebrow">最近执行</span>{runs.slice(0, 6).map(run => <div className="schedule-run" key={run.id}><span>{run.localDate} · {run.action === 'open' ? '开群' : '关群'}</span><em className={run.success ? 'enabled' : ''}>{run.success ? '成功' : `失败${run.error ? `：${run.error}` : ''}`}</em></div>)}</div>}</div> : <EmptyState title="选择计划" detail="每日开群/关群计划默认停用，启用后才会执行。" />}</div> }
function toLocalInput(value?: string | null) { if (!value) return ''; const date = new Date(value); const pad = (number: number) => String(number).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` }
