import { useEffect, useState } from 'react'
import { Download, Pencil, Plus, RefreshCw, Save, ShieldCheck, Trash2, Upload } from 'lucide-react'
import { api, readableError } from '../api/client'
import { EmptyState, PageFeedback, SectionHeading } from '../components/PageState'
import type { Group, Rule } from '../types'

const actionLabels: Record<string, string> = { recall: '撤回', mute: '禁言', remove: '移出', blacklist: '拉黑', notify: '提示' }
const matcherLabels: Record<string, string> = { contains: '包含关键词', exact: '精确匹配', prefix: '前缀匹配', regex: '正则表达式', semantic: 'AI 语义' }

function blankRule(accountId: string): Rule { return { id: 0, accountId, groupId: 0, name: '新规则', matcher: 'contains', pattern: '', threshold: 0, count: 0, windowSeconds: 0, cooldownSeconds: 0, priority: 100, mode: 'observe', enabled: false, semanticThreshold: 0.8, exemptRoles: ['owner', 'admin'], exemptUserIds: [], actions: [{ kind: 'recall', durationSeconds: 0, message: '' }] } }

export default function RulesPage({ accountId, groups, onError }: { accountId: string; groups: Group[]; onError: (value: string) => void }) {
  const [rules, setRules] = useState<Rule[]>([]); const [selected, setSelected] = useState<number | null>(null); const [state, setState] = useState<'idle'|'loading'|'empty'|'ready'|'error'>('idle'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const reload = async () => { if (!accountId) { setState('empty'); return }; setState('loading'); try { const result = await api.listRules(accountId); setRules(result); setSelected(current => current && result.some(rule => rule.id === current) ? current : result[0]?.id ?? null); setState(result.length ? 'ready' : 'empty') } catch (reason) { setError(readableError(reason)); setState('error') } }
  useEffect(() => { void reload() }, [accountId])
  const current = rules.find(rule => rule.id === selected) || null
  const update = (patch: Partial<Rule>) => { if (!current) return; setRules(values => values.map(rule => rule.id === current.id ? { ...rule, ...patch } : rule)) }
  const create = () => { const rule = blankRule(accountId); setRules(values => [...values, rule]); setSelected(0); setState('ready') }
  const save = async () => { if (!current || !current.name.trim() || !current.pattern.trim()) { onError('规则名称和匹配内容不能为空'); return }; setSaving(true); try { const id = await api.saveRule(current); setRules(values => values.map(rule => rule === current ? { ...rule, id } : rule)); setSelected(id); await reload() } catch (reason) { onError(readableError(reason)) } finally { setSaving(false) } }
  const remove = async () => { if (!current?.id || !window.confirm(`确认删除规则“${current.name}”？`)) return; try { await api.deleteRule(accountId, current.id); await reload() } catch (reason) { onError(readableError(reason)) } }
  const exportRules = async () => { try { const payload = await api.exportRules(accountId, rules); download('dh-rules.json', payload) } catch (reason) { onError(readableError(reason)) } }
  const importRules = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = async () => { try { const content = String(reader.result); const parsed = JSON.parse(content); if (!Array.isArray(parsed?.rules)) throw new Error('JSON 中没有 rules 数组'); const automatic = parsed.rules.filter((rule: Rule) => rule.mode === 'automatic' && rule.enabled).length; if (automatic && !window.confirm(`文件中有 ${automatic} 条已启用自动规则，确认导入？`)) return; await api.importRules(accountId, content); await reload(); onError(`已导入 ${parsed.rules.length} 条规则`) } catch (reason) { onError(`导入失败：${readableError(reason)}`) } }; reader.readAsText(file); event.target.value = '' }
  return <div className="page-stack"><section className="section"><SectionHeading eyebrow="确定性群管" title="规则" meta={`${rules.length} 条`} actions={<div className="button-row"><button className="secondary" onClick={() => void reload()}><RefreshCw size={15} />刷新</button><button className="secondary" onClick={exportRules}><Download size={15} />导出 JSON</button><label className="secondary file-button"><Upload size={15} />导入 JSON<input type="file" accept="application/json" onChange={importRules} /></label><button className="primary" onClick={create}><Plus size={15} />新建规则</button></div>} />
      <PageFeedback state={state} error={error} retry={() => void reload()} emptyTitle="规则为空" emptyDetail="新库默认不启用规则。可新建规则或导入兼容模板。"><div className="split-editor"><div className="rule-list">{rules.map(rule => <button className={`rule-list-item ${rule.id === selected ? 'selected' : ''}`} onClick={() => setSelected(rule.id)} key={`${rule.id}-${rule.name}`}><ShieldCheck size={15} /><span><strong>{rule.name}</strong><small>{matcherLabels[rule.matcher] || rule.matcher} · {rule.mode === 'automatic' ? '自动执行' : '观察模式'}</small></span><em className={rule.enabled ? 'enabled' : ''}>{rule.enabled ? '启用' : '停用'}</em></button>)}</div>{current ? <RuleEditor rule={current} groups={groups} onChange={update} onSave={() => void save()} onDelete={() => void remove()} saving={saving} /> : <EmptyState title="选择一条规则" detail="左侧选择规则后编辑匹配条件和动作。" />}</div></PageFeedback></section></div>
}

function RuleEditor({ rule, groups, onChange, onSave, onDelete, saving }: { rule: Rule; groups: Group[]; onChange: (patch: Partial<Rule>) => void; onSave: () => void; onDelete: () => void; saving: boolean }) {
  const setAction = (kind: string, enabled: boolean) => { const actions = enabled ? [...rule.actions, { kind, durationSeconds: kind === 'mute' ? 600 : 0, message: '' }] : rule.actions.filter(action => action.kind !== kind); onChange({ actions }) }
  return <div className="editor-panel"><div className="editor-title"><div><span className="eyebrow">规则编辑</span><h3>{rule.name || '未命名规则'}</h3></div><div className="button-row"><button className="secondary" onClick={onDelete} disabled={!rule.id}><Trash2 size={15} />删除</button><button className="primary" onClick={onSave} disabled={saving}><Save size={15} />{saving ? '保存中' : '保存规则'}</button></div></div><div className="form-grid"><label>规则名称<input value={rule.name} onChange={event => onChange({ name: event.target.value })} /></label><label>作用群<select value={rule.groupId} onChange={event => onChange({ groupId: Number(event.target.value) })}><option value={0}>全局规则</option>{groups.map(group => <option value={group.groupId} key={group.groupId}>{group.name}</option>)}</select></label><label>匹配方式<select value={rule.matcher} onChange={event => onChange({ matcher: event.target.value })}>{Object.entries(matcherLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>优先级<input type="number" min={0} max={999} value={rule.priority} onChange={event => onChange({ priority: Number(event.target.value) })} /></label><label className="wide-field">匹配内容<textarea value={rule.pattern} onChange={event => onChange({ pattern: event.target.value })} placeholder="例如：广告、诈骗链接或正则表达式" /></label><label>时间窗口（秒）<input type="number" min={0} value={rule.windowSeconds} onChange={event => onChange({ windowSeconds: Number(event.target.value) })} /></label><label>冷却时间（秒）<input type="number" min={0} value={rule.cooldownSeconds} onChange={event => onChange({ cooldownSeconds: Number(event.target.value) })} /></label><label>语义阈值<input type="number" min={0} max={1} step={0.05} value={rule.semanticThreshold} onChange={event => onChange({ semanticThreshold: Number(event.target.value) })} /></label></div><div className="editor-section"><span className="eyebrow">执行控制</span><div className="toggle-row"><label className="switch-field"><input type="checkbox" checked={rule.enabled} onChange={event => onChange({ enabled: event.target.checked })} /><span>启用规则</span></label><label className="switch-field"><input type="checkbox" checked={rule.mode === 'automatic'} onChange={event => onChange({ mode: event.target.checked ? 'automatic' : 'observe' })} /><span>自动执行（默认观察）</span></label></div><div className="action-checks">{Object.entries(actionLabels).map(([kind, label]) => <label key={kind}><input type="checkbox" checked={rule.actions.some(action => action.kind === kind)} onChange={event => setAction(kind, event.target.checked)} />{label}{kind === 'mute' && rule.actions.some(action => action.kind === 'mute') && <input className="duration-input" type="number" min={1} value={rule.actions.find(action => action.kind === 'mute')?.durationSeconds || 600} onChange={event => onChange({ actions: rule.actions.map(action => action.kind === 'mute' ? { ...action, durationSeconds: Number(event.target.value) } : action) })} />} </label>)}</div></div></div>
}

function download(name: string, content: string) { const blob = new Blob([content], { type: 'application/json;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url) }
