import { useState } from 'react'
import { Send } from 'lucide-react'
import { invoke } from '@tauri-apps/api/core'
import RuntimeControls from '@runtime-controls'
import type { Diagnostic } from '../runtimeTypes'
import type { AiSettings, DatabaseStatus } from '../types'
import { readableError } from '../api/client'

export default function SettingsPage({ diagnostic, database, aiSettings, setAiSettings, refresh, onError }: { diagnostic: Diagnostic | null; database: DatabaseStatus | null; aiSettings: AiSettings; setAiSettings: (value: AiSettings) => void; refresh: () => Promise<void>; onError: (value: string) => void }) {
  const [apiKey, setApiKey] = useState(''); const [question, setQuestion] = useState(''); const [reply, setReply] = useState(''); const [busy, setBusy] = useState(false)
  const save = async () => { setBusy(true); onError(''); try { await invoke('save_ai_settings', { baseUrl: aiSettings.base_url, webhookUrl: aiSettings.webhook_url, model: aiSettings.model, apiKey: apiKey || null }); setApiKey(''); await refresh() } catch (reason) { onError(readableError(reason)) } finally { setBusy(false) } }
  const test = async () => { if (!question.trim()) return; setBusy(true); setReply(''); try { const result = await invoke<{ decision: { reply: string; reason: string; confidence: number }; elapsedMs: number; model: string }>('test_ai', { message: question, recentContext: [] }); setReply(`${result.decision.reply || 'AI 没有返回文字回复'}\n\n理由：${result.decision.reason || '未说明'}\n置信度：${Math.round(result.decision.confidence * 100)}%\n模型：${result.model} · ${result.elapsedMs}ms`) } catch (reason) { onError(readableError(reason)) } finally { setBusy(false) } }
  return <div className="page-stack"><section className="section settings-grid"><RuntimeControls diagnostic={diagnostic} loading={busy} refresh={refresh} setError={onError} /><div><span className="eyebrow">AI 提供商</span><h2>连接设置</h2><label>Base URL<input value={aiSettings.base_url} onChange={event => setAiSettings({ ...aiSettings, base_url: event.target.value })} placeholder="https://example.com/v1" /></label><label>Webhook URL<input value={aiSettings.webhook_url} onChange={event => setAiSettings({ ...aiSettings, webhook_url: event.target.value })} placeholder="可留空" /></label><label>模型<input value={aiSettings.model} onChange={event => setAiSettings({ ...aiSettings, model: event.target.value })} placeholder="deepseek-v4-pro" /></label><label>API Key<input type="password" value={apiKey} onChange={event => setApiKey(event.target.value)} placeholder={aiSettings.api_key_configured ? '已保存，留空保持原值' : '尚未设置'} /></label><button className="primary" onClick={() => void save()} disabled={busy}>保存 AI 设置</button></div></section><section className="section"><span className="eyebrow">AI 离群测试</span><h2>测试当前模型</h2><p className="muted">此处不读取群消息，也不会执行回复、撤回、禁言或移出。</p><textarea value={question} onChange={event => setQuestion(event.target.value)} placeholder="输入一条测试问题" /><button className="primary" onClick={() => void test()} disabled={busy || !question.trim()}><Send size={15} />测试 AI</button>{reply && <pre className="ai-result">{reply}</pre>}</section><section className="section"><span className="eyebrow">运行信息</span><h2>数据库与协议</h2><dl className="runtime-details"><dt>数据库</dt><dd>{database?.path || '未打开'}</dd><dt>Schema</dt><dd>{database?.schemaVersion ?? '-'}</dd><dt>完整性</dt><dd>{database?.integrity || '-'}</dd><dt>当前页面</dt><dd>{diagnostic?.pageTitle || '-'}</dd><dt>页面地址</dt><dd>{diagnostic?.pageUrl || '-'}</dd><dt>NIM 账号</dt><dd>{diagnostic?.nimAccount || '未识别'}</dd></dl></section></div>
}
